[package]
name = "embedded-midi"
version = "0.0.1"
authors = ["Mendelt Siebenga <msiebenga@gmail.com>"]
edition = "2018"
publish = false

[badges]
travis-ci = { repository = "mendelt/embedded-midi" }

[dependencies]
nb = "0.1.2"
embedded-hal = "0.2.3"

